name: Build and Deploy Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Execute using Makefile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: make pkg

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz --delete out/runner ${{ secrets.REMOTE_DEST }}

      - name: Execute Commands on Remote Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            mkdir -p ~/.config/systemd/user
            cp ~/runner/runner.service ~/.config/systemd/user/
            systemctl --user daemon-reload
            systemctl --user restart runner.service
            systemctl --user status runner.service
          EOF
